name: Retail-Classic-Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Retail and Classic
      run: sudo .release/release.sh -d -l -g
    # - name: Build Classic
    #   run: .release/release.sh -d -l -g
