name: Retail-Classic-Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: List dir
      run: pwd && ls -al
    - name: Change dir and list content
      run: pwd && ls -al
    - name: Build Retail
      run: pwd && ls -al && sudo bash ./release.sh -d -l
      shell: bash
    - name: Build Classic
      run: pwd && ls -al && sudo bash ./release.sh -d -l -g 1.13.3
      shell: bash
      working-directory: ./.release
    - name: Check build results
      run: pwd && ls -al
      working-directory: ./.release
    - name: Check build results 2
      run: pwd && ls -al
