name: Retail-Classic-Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: List dir
      run: pwd && ls -al
    - name: Build Retail and Classic
      run: cd ./.release && sudo ./release.sh -d -l -g
    # - name: Build Classic
    #   run: .release/release.sh -d -l -g
