name: Retail-Classic-Build on dev branch push

on:
  push:
    branches-ignore:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    # run release.sh without any arguments (default)
    - uses: BigWigsMods/packager@master
      name: Build Retail using BigWigsMods/packager@master NO UPLOAD
      with:
        args: release.sh -d -l

    - uses: BigWigsMods/packager@master
      name: Build Classic using BigWigsMods/packager@master NO UPLOAD
      with:
        args: release.sh -d -l -g 1.13.3

    - name: Check created files
      shell: bash
      run: ls -aRl
      working-directory: ./.release

    - name: Get zip info
      shell: bash
      run: zipinfo "*.zip"
      working-directory: ./.release

    # - uses: BigWigsMods/packager@master
    #   name: Build Retail using BigWigsMods/packager@master WITH UPLOAD
    #   with:
    #     args: release.sh -l

    # - uses: BigWigsMods/packager@master
    #   name: Build Classic using BigWigsMods/packager@master WITH UPLOAD
    #   with:
    #     args: release.sh -l -g 1.13.3

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

