name: Retail-Classic-Build on dev branch push

on:
  push:
    branches-ignore:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set env with Curse Forge API key
      shell: bash
      run: sudo echo "::set-env name=CF_API_KEY::${{ secrets.CF_API_KEY }}"

    - name: Store Curse Forge API key into a .env file
      shell: bash
      run: sudo echo "CF_API_KEY=${CF_API_KEY}" > ./.env && ls -al
      # working-directory: ./.release

    # run release.sh without any arguments (default)
    - uses: BigWigsMods/packager@master
      name: Build Retail using BigWigsMods/packager@master NO UPLOAD
      with:
        args: release.sh -d -l

    - uses: BigWigsMods/packager@master
      name: Build Classic using BigWigsMods/packager@master NO UPLOAD
      with:
        args: release.sh -d -l -g 1.13.3

    - name: Check created files
      shell: bash
      run: ls -al

    - name: Unzip all
      shell: bash
      run: unzip "*.zip"
      working-directory: ./.release

    - name: Recursive list unzipped files
      shell: bash
      run: ls -aRl
      working-directory: ./.release

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

